# 创建新的 docker-compose.yml
services:
  web:
    build: .
    ports:
      - "8085:80"
    volumes:
      - ./src/tp8:/var/www/html/tp8
    environment:
      - APP_DEBUG=true
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tp8
      MYSQL_USER: tp8user
      MYSQL_PASSWORD: tp8pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: